/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mysqlwork;

import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Contact_6 extends javax.swing.JFrame {

    private String s1;
    private String s2;
    private String s3;
    private String s4;
    private String s5;
    Connect co;
    ResultSet rs;
    private int m = 0;
    /**
     * Creates new form Contact
     */
    private static Contact_6 c = null;

    private Contact_6() {
        initComponents();
    }

    public synchronized static Contact_6 getC() {
        if (c == null) {
            c = new Contact_6();
            c.setLocationRelativeTo(null);
            c.getContentPane().setBackground(new Color(150, 200, 200));
        }
        return c;
    }

    private void queryinfo() {
        try {
            // TODO add your handling code here:
            s1 = jTextField1.getText();
            s2 = jTextField2.getText();
            s3 = jTextField3.getText();
            s4 = jTextField4.getText();
            s5 = jTextField5.getText();
            co = new Connect();

            if (s1 != null) {
                rs = co.connect("select * from contact where coname='" + s1 + "'");
            } else if (s2 != null) {
                rs = co.connect("select * from contact where phone='" + s2 + "'");
            } else if (s3 != null) {
                rs = co.connect("select * from contact where telephone='" + s3 + "'");
            } else if (s4 != null) {
                rs = co.connect("select * from contact where email='" + s4 + jComboBox1.getItemAt(jComboBox1.getSelectedIndex()) + "'");
            } else if (s5 != null) {
                rs = co.connect("select * from contact where company='" + s5 + "'");
            }
            int i = 0, j = 0;
            while (rs.next()) {
                for (int k = 1; k <= 5; k++) {
                    this.jTable1.setValueAt(rs.getString(k), i, j + k - 1);
                }
                i++;
            }
            while (i < 8) {
                for (int k = 1; k <= 5; k++) {
                    this.jTable1.setValueAt(null, i, j + k - 1);

                }
                i++;
            }
            co.con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("联系人信息");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "姓名", "电话", "手机", "邮箱", "所属公司"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("姓名");

        jLabel3.setText("电话");

        jLabel4.setText("手机");

        jLabel5.setText("邮箱");

        jLabel6.setText("所属公司");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "@qq.com", "@163.com" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("查询");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("添加");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("删除");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("修改");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)))
                                .addGap(18, 18, 18)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        c.queryinfo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (p1.getPp().isB3()) {
            JOptionPane.showMessageDialog(this, "没有操作权限！", null, JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                // TODO add your handling code here:
                s1 = jTextField1.getText();
                s2 = jTextField2.getText();
                s3 = jTextField3.getText();
                s4 = jTextField4.getText();
                s5 = jTextField5.getText();
                co = new Connect();
                if (!s1.equals("")) {
                    co.sql.execute("INSERT INTO `databasework`.`contact` (`coname`, `phone`, `telephone`, `email`, `company`) VALUES ('" + s1 + "', '" + s2 + "', '" + s3 + "', '" + s4 + jComboBox1.getItemAt(m) + "', '" + s5 + "')");
                    JOptionPane.showMessageDialog(this, "添加成功!", null, JOptionPane.INFORMATION_MESSAGE);
                    c.queryinfo();
                } else {
                    JOptionPane.showMessageDialog(this, "联系人姓名为空，无法添加！!", null, JOptionPane.WARNING_MESSAGE);
                }
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (p1.getPp().isB3()) {
            JOptionPane.showMessageDialog(this, "没有操作权限！", null, JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                // TODO add your handling code here:
                co = new Connect();
                if (co.connect("select * from contact where coname ='" + s1 + "'") != null) {
                    co.sql.execute("delete from contact where coname ='" + s1 + "'");
                } else if (co.connect("select * from contact where phone='" + s2 + "'") != null) {
                    co.sql.execute("delete from contact where phone='" + s2 + "'");
                } else if (co.connect("select * from contact where telephone='" + s3 + "'") != null) {
                    co.sql.execute("delete from contact where telephone='" + s3 + "'");
                } else if (co.connect("select * from contact where email='" + s4 + jComboBox1.getItemAt(jComboBox1.getSelectedIndex()) + "'") != null) {
                    co.sql.execute("delete from contact where email='" + s4 + jComboBox1.getItemAt(jComboBox1.getSelectedIndex()) + "'");
                } else if (co.connect("select * from contact where company='" + s5 + "'") != null) {
                    co.sql.execute("delete from contact where company='" + s5 + "'");
                }

                JOptionPane.showMessageDialog(this, "删除成功！", null, JOptionPane.INFORMATION_MESSAGE);
                c.queryinfo();
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (p1.getPp().isB3()) {
            JOptionPane.showMessageDialog(this, "没有操作权限！", null, JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                s1 = this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 0).toString();
                jTextField1.setText(s1);
                s2 = jTextField2.getText();
                s3 = jTextField3.getText();
                s4 = jTextField4.getText();
                s5 = jTextField5.getText();
                // TODO add your handling code here:
                Connect co = new Connect();
                String sss;
                int flag = 0;
                ResultSet rs1 = co.connect("SELECT * FROM databasework.contact");
                while (rs1.next()) {
                    sss = rs1.getString(1);
                    if (s1.equals(sss)) {
                        if (!s2.equals("")) {
                            co.sql.execute("UPDATE `databasework`.`contact` SET `phone`='" + s2 + "' WHERE `coname`='" + s1 + "'");
                        }
                        if (!s3.equals("")) {
                            co.sql.execute("UPDATE `databasework`.`contact` SET  `telephone`='" + s3 + "' WHERE `coname`='" + s1 + "'");
                        }
                        if (!s4.equals("")) {
                            co.sql.execute("UPDATE `databasework`.`contact` SET  `email`='" + s4 + jComboBox1.getItemAt(jComboBox1.getSelectedIndex()) + "' WHERE `coname`='" + s1 + "'");
                        }
                        if (!s5.equals("")) {
                            co.sql.execute("UPDATE `databasework`.`contact` SET  `company`='" + s5 + "' WHERE `coname`='" + s1 + "'");
                        }
                        flag = 1;
                        break;
                    }
                }
                if (flag == 0) {
                    co.sql.execute("INSERT INTO contact VALUES ('" + s1 + "','" + s2 + "','" + s3 + "','" + s4 + jComboBox1.getItemAt(jComboBox1.getSelectedIndex()) + "','" + s5 + "')");

                }
                JOptionPane.showMessageDialog(this, "更新成功!", null, JOptionPane.INFORMATION_MESSAGE);
                c.queryinfo();
            } catch (Exception e) {
                System.out.println(e);
            }
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        m = jComboBox1.getSelectedIndex();;
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
