/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mysqlwork;

import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Customerinfo_9 extends javax.swing.JFrame {

    /**
     * Creates new form Querycusinfo
     */
    private static Customerinfo_9 info = null;
    private String ss1, ss2;

    public String getSs2() {
        return ss2;
    }
    private int f = 0;

    public int getF() {
        return f;
    }

    private Customerinfo_9() {
        initComponents();
    }

    public String getSs1() {
        return ss1;
    }

    public synchronized static Customerinfo_9 getInfo() {
        if (info == null) {
            info = new Customerinfo_9();
            info.setLocationRelativeTo(null);
            info.getContentPane().setBackground(new Color(150, 200, 200));
        }
        return info;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("客户信息");

        jButton1.setText("查询");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("添加");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("删除");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("更新");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "企业名称", "企业法人", "客户简称", "开户银行", "企业地址", "邮政编码", "账号"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("输入ALL查询全部客户信息");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jButton3)
                            .addComponent(jButton2)
                            .addComponent(jButton4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 308, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addComponent(jScrollPane1))))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(41, 41, 41)
                        .addComponent(jButton2)
                        .addGap(36, 36, 36)
                        .addComponent(jButton3)
                        .addGap(33, 33, 33)
                        .addComponent(jButton4)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void data() {
        try {
            // TODO add your handling code here:
            String s1 = jTextField1.getText();
            Connect c = new Connect();

            ResultSet rs = c.connect("select * from customer");
            int i = 0, j = 0;
            while (rs.next()) {
                for (int k = 1; k <= 7; k++) {
                    this.jTable1.setValueAt(rs.getString(k), i, j + k - 1);
                }
                i++;
            }
            while (i < 8) {
                for (int k = 1; k <= 7; k++) {
                    this.jTable1.setValueAt(null, i, j + k - 1);
                }
                i++;
            }

        } catch (Exception e) {
            System.out.println(e);
        }

    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            String s1 = jTextField1.getText();
            Connect c = new Connect();
            if (s1.equals("ALL")) {
                info.data();
            } else {
                ResultSet rs1 = c.connect("select * from customer where (cusname like '%" + s1 + "%')or (legalperson like '%" + s1 + "%')or (abbreviation like '%" + s1 + "%')or (bank like '%" + s1 + "%')or (address like '%" + s1 + "%')or (postcode like '%" + s1 + "%')or (accountnum like '%" + s1 + "%')");
                int i = 0, j = 0;
                while (rs1.next()) {
                    for (int k = 1; k <= 7; k++) {
                        this.jTable1.setValueAt(rs1.getString(k), i, j + k - 1);
                    }
                    i++;
                }
                while (i < 8) {
                    for (int k = 1; k <= 7; k++) {
                        this.jTable1.setValueAt(null, i, j + k - 1);

                    }
                    i++;
                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        f = 1;
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Insertcus_8.getInfo().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:

            String s1 = this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 0).toString();

            Connect c = new Connect();
            if (c.connect("select * from customer where cusname ='" + s1 + "'") != null) {
                c.sql.execute("delete from customer where cusname ='" + s1 + "'");

            } else {
                JOptionPane.showMessageDialog(this, "该项数据不存在!", null, JOptionPane.WARNING_MESSAGE);
            }
            info.data();
            JOptionPane.showMessageDialog(this, "删除成功!", null, JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        f = 2;
        ss1 = this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 0).toString();
        ss2 = this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 1).toString();
        if (ss1 != null) {
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    Insertcus_8.getInfo().setVisible(true);
                }
            });
            info.data();
        } else {
            JOptionPane.showMessageDialog(this, "没有可以更新的联系人！", null, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
